services:
  web:
    build: .
    container_name: Flight_TODO
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    depends_on:
      db:
        condition: service_healthy

  tailwind:
    build: .
    command: python manage.py tailwind start
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - .:/app
    depends_on:
      - web

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5