services:
  web:
    build: .
    container_name: Flight_TODO
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

  tailwind:
    build: .
    command: python manage.py tailwind start
    volumes:
      - .:/app
    depends_on:
      - web

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres,
      - POSTGRES_USER=dbuser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 5s
      timeout: 5s
      retries: 5