# Generated by Django 6.0.3 on 2026-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('origin_icao', models.CharField(blank=True, max_length=4)),
                ('dest', models.CharField(max_length=200)),
                ('dest_icao', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
