# Generated by Django 6.0.3 on 2026-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightTODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
